name: publish

on:
    push:
        branches:
            - master

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14
            - run: |
                  npm ci
                  npm run test
              env:
                  CI: true
                  NPM_PRIVATE_READ: ${{ secrets.NPM_PRIVATE_READ }}

    npm-publish:
        needs: build-and-test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14
            - run: |
                  npm ci
                  npm run build
              env:
                  CI: true
                  NPM_PRIVATE_READ: ${{ secrets.NPM_PRIVATE_READ }}
            - name: 'Semantic Release'
              uses: cycjimmy/semantic-release-action@v2
              id: semantic
              with:
                  branch: master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  NPM_PRIVATE_READ: ${{ secrets.NPM_TOKEN }}
